export const roles = [
  { id: 'role-superadmin', name: 'Super Administrator', code: 'super_admin', description: 'Full system ownership and root control', is_system: 1 },
  { id: 'role-admin', name: 'Admin', code: 'admin', description: 'Organization management, users, teams, inventory', is_system: 1 },
  { id: 'role-manager', name: 'Sales Manager', code: 'sales_manager', description: 'Department-wide sales oversight and targets', is_system: 1 },
  { id: 'role-leader', name: 'Team Leader', code: 'team_leader', description: 'Pod management and daily lead dispatching', is_system: 1 },
  { id: 'role-executive', name: 'Sales Executive', code: 'sales_executive', description: 'Lead handling, deal closing, telecalling queue', is_system: 1 },
  { id: 'role-inventory', name: 'Inventory Manager', code: 'inventory_manager', description: 'Stock movements, warehouses, suppliers', is_system: 1 },
  { id: 'role-finance', name: 'Finance Manager', code: 'finance_manager', description: 'Payment tracking, invoice verification', is_system: 1 },
  { id: 'role-support', name: 'Customer Support', code: 'support', description: 'Customer tickets and lead support', is_system: 1 },
  { id: 'role-readonly', name: 'Auditor / Read Only', code: 'auditor', description: 'View-only access for reporting and audits', is_system: 1 }
];

export const permissionsList = [
  { code: 'users.view', name: 'View Users', category: 'User Management' },
  { code: 'users.create', name: 'Create Users', category: 'User Management' },
  { code: 'users.edit', name: 'Edit Users', category: 'User Management' },
  { code: 'users.delete', name: 'Delete Users', category: 'User Management' },
  { code: 'roles.view', name: 'View Roles & Matrix', category: 'Role Management' },
  { code: 'roles.manage', name: 'Manage Role Permissions', category: 'Role Management' },
  { code: 'teams.view_all', name: 'View All Teams', category: 'Team Management' },
  { code: 'teams.view_own', name: 'View Own Team', category: 'Team Management' },
  { code: 'teams.manage', name: 'Manage Teams & Targets', category: 'Team Management' },
  { code: 'leads.view_all', name: 'View All Leads', category: 'Lead Management' },
  { code: 'leads.view_team', name: 'View Team Leads', category: 'Lead Management' },
  { code: 'leads.view_own', name: 'View Assigned Leads', category: 'Lead Management' },
  { code: 'leads.create', name: 'Create Leads', category: 'Lead Management' },
  { code: 'leads.edit', name: 'Edit Leads', category: 'Lead Management' },
  { code: 'leads.delete', name: 'Delete Leads', category: 'Lead Management' },
  { code: 'leads.assign', name: 'Assign Leads', category: 'Lead Management' },
  { code: 'leads.request', name: 'Request Leads from Admin', category: 'Lead Management' },
  { code: 'leads.import_export', name: 'Import / Export Leads', category: 'Lead Management' },
  { code: 'customers.view', name: 'View Customers', category: 'Customer Management' },
  { code: 'customers.create', name: 'Create Customers', category: 'Customer Management' },
  { code: 'customers.edit', name: 'Edit Customers', category: 'Customer Management' },
  { code: 'customers.delete', name: 'Delete Customers', category: 'Customer Management' },
  { code: 'sales.view_all', name: 'View All Sales', category: 'Sales & Orders' },
  { code: 'sales.view_team', name: 'View Team Sales', category: 'Sales & Orders' },
  { code: 'sales.view_own', name: 'View Own Sales', category: 'Sales & Orders' },
  { code: 'sales.create', name: 'Create Sales Order', category: 'Sales & Orders' },
  { code: 'sales.edit', name: 'Edit Sales Order', category: 'Sales & Orders' },
  { code: 'sales.delete', name: 'Delete Sales Order', category: 'Sales & Orders' },
  { code: 'payments.view_all', name: 'View All Payments', category: 'Payments' },
  { code: 'payments.view_team', name: 'View Team Payments', category: 'Payments' },
  { code: 'payments.view_own', name: 'View Own Payments', category: 'Payments' },
  { code: 'payments.record', name: 'Record Payments', category: 'Payments' },
  { code: 'payments.verify', name: 'Verify & Approve Payments', category: 'Payments' },
  { code: 'inventory.view', name: 'View Products & Stock', category: 'Inventory' },
  { code: 'inventory.manage', name: 'Manage & Adjust Stock', category: 'Inventory' },
  { code: 'inventory.transfer', name: 'Warehouse Transfers', category: 'Inventory' },
  { code: 'reports.view_all', name: 'View All Reports', category: 'Reports' },
  { code: 'reports.view_team', name: 'View Team Reports', category: 'Reports' },
  { code: 'reports.submit_daily', name: 'Submit Daily Report', category: 'Reports' },
  { code: 'reports.whatsapp', name: 'Send WhatsApp Digest', category: 'Reports' },
  { code: 'chat.view', name: 'Access Team Chat', category: 'Communication' },
  { code: 'announcements.create', name: 'Create Announcements', category: 'Communication' },
  { code: 'settings.manage', name: 'Manage System Settings', category: 'Settings' },
  { code: 'integrations.manage', name: 'Manage Meta & WhatsApp API', category: 'Integrations' },
  { code: 'audit.view', name: 'View System Audit Logs', category: 'Security' }
];

export const teamsData = [
  { id: 'team-alpha', name: 'Team Alpha', code: 'ALPHA', target: 400000 },
  { id: 'team-bravo', name: 'Team Bravo', code: 'BRAVO', target: 350000 },
  { id: 'team-charlie', name: 'Team Charlie', code: 'CHARLIE', target: 250000 },
  { id: 'team-delta', name: 'Team Delta', code: 'DELTA', target: 200000 },
  { id: 'team-echo', name: 'Team Echo', code: 'ECHO', target: 150000 }
];

export const categories = [
  { id: 'cat-yantra', name: 'All Yantra', code: 'YANTRA', description: 'Sacred energized geometric copper, silver and gold yantras' },
  { id: 'cat-bracelet', name: 'Bracelet', code: 'BRACELET', description: 'Karungali, gemstone and sacred wood healing bracelets' },
  { id: 'cat-chowki', name: 'Chowki', code: 'CHOWKI', description: 'Ashta Lakshmi & Dasha Mahavidya brass & gold plated chowkis' },
  { id: 'cat-general', name: 'General', code: 'GEN', description: 'Photo frames, malas, statues, Saligrama, and spiritual accessories' },
  { id: 'cat-kit', name: 'Kit', code: 'KIT', description: 'Complete Bagalamukhi, Dhanalakshmi, Nazar, and Shani worship kits' },
  { id: 'cat-ring', name: 'Ring', code: 'RING', description: 'Navaratna, Meru, Drusti, and certified astrological gemstone rings' }
];

export const warehouses = [
  { id: 'wh-blr', name: 'Bangalore Central Warehouse', code: 'WH-BLR', location: 'Whitefield, Bangalore', contact: '+91 80 4001 2000' },
  { id: 'wh-hbl', name: 'Hubli Regional Hub', code: 'WH-HBL', location: 'Gokul Road, Hubli', contact: '+91 836 220 1000' },
  { id: 'wh-mys', name: 'Mysore Logistics Center', code: 'WH-MYS', location: 'Hebbal Ind. Estate, Mysore', contact: '+91 821 240 3000' }
];

export const suppliers = [
  { id: 'sup-apex', name: 'Vedic Craft Suppliers Ltd', contact_name: 'Harish Mehta', phone: '+91 99001 22334', email: 'sales@vediccrafts.in', address: 'Bangalore' },
  { id: 'sup-zenith', name: 'Divine Gem & Yantra Works', contact_name: 'Kunal Singhal', phone: '+91 99001 55667', email: 'orders@divinegem.com', address: 'Mumbai' },
  { id: 'sup-nexa', name: 'Astro Products Direct', contact_name: 'Anita Fernandez', phone: '+91 99001 88990', email: 'supply@astroproducts.com', address: 'Chennai' }
];

export const rawProductsList = [
  { name: 'Bagalamukhi Yantra', sku: '0001', category: 'cat-yantra', price: 1500, stock: 50 },
  { name: 'Bagalamukhi Yantra', sku: '0002', category: 'cat-yantra', price: 1000, stock: 100 },
  { name: 'Dhanvantri Yanthra', sku: '0003', category: 'cat-yantra', price: 1500, stock: 32 },
  { name: 'Dhanvantri Yanthra', sku: '0004', category: 'cat-yantra', price: 1000, stock: 55 },
  { name: 'Durga Yantra', sku: '0005', category: 'cat-yantra', price: 1500, stock: 0 },
  { name: 'Durga Yantra', sku: '0006', category: 'cat-yantra', price: 1000, stock: 5 },
  { name: 'Kalasarpa Yantra', sku: '0007', category: 'cat-yantra', price: 1500, stock: 20 },
  { name: 'Kalasarpa Yantra', sku: '0008', category: 'cat-yantra', price: 1000, stock: 70 },
  { name: 'Kubera Yantra', sku: '0009', category: 'cat-yantra', price: 1500, stock: 25 },
  { name: 'Kubera Yantra', sku: '0010', category: 'cat-yantra', price: 1000, stock: 72 },
  { name: 'Lagna Yog Yantra', sku: '0011', category: 'cat-yantra', price: 1500, stock: 40 },
  { name: 'Lagna Yog Yantra', sku: '0012', category: 'cat-yantra', price: 1000, stock: 40 },
  { name: 'Lakshminarayana Yantra', sku: '0013', category: 'cat-yantra', price: 1500, stock: 5 },
  { name: 'Lakshminarayana Yantra', sku: '0014', category: 'cat-yantra', price: 1000, stock: 5 },
  { name: 'Maha Mrityunjay Yantra', sku: '0015', category: 'cat-yantra', price: 1500, stock: 1 },
  { name: 'Maha Mrityunjay Yantra', sku: '0016', category: 'cat-yantra', price: 1000, stock: 1 },
  { name: 'Mahalakshmi Yanthra', sku: '0017', category: 'cat-yantra', price: 1500, stock: 0 },
  { name: 'Mahalakshmi Yanthra', sku: '0018', category: 'cat-yantra', price: 1000, stock: 220 },
  { name: 'Navagraha Yantra', sku: '0019', category: 'cat-yantra', price: 1500, stock: 0 },
  { name: 'Navagraha Yantra', sku: '0020', category: 'cat-yantra', price: 1000, stock: 5 },
  { name: 'Santana Gopala Yantra', sku: '0021', category: 'cat-yantra', price: 1500, stock: 60 },
  { name: 'Santhana Gopala Yantra', sku: '0022', category: 'cat-yantra', price: 1000, stock: 40 },
  { name: 'Sarasvati Yantra', sku: '0023', category: 'cat-yantra', price: 1000, stock: 40 },
  { name: 'Saraswati Yantra', sku: '0024', category: 'cat-yantra', price: 1500, stock: 20 },
  { name: 'Sarv Karya Siddhi Yantra', sku: '0025', category: 'cat-yantra', price: 1500, stock: 200 },
  { name: 'Sarv Karya Siddhi Yantra', sku: '0026', category: 'cat-yantra', price: 1000, stock: 50 },
  { name: 'Shree Yantra', sku: '0027', category: 'cat-yantra', price: 1500, stock: 0 },
  { name: 'Shree Yantra', sku: '0028', category: 'cat-yantra', price: 1000, stock: 5 },
  { name: 'Sudarshana Yantra', sku: '0029', category: 'cat-yantra', price: 1500, stock: 25 },
  { name: 'Sudarshana Yantra', sku: '0030', category: 'cat-yantra', price: 1000, stock: 35 },
  { name: 'Vastu Dosha Nivarana Yanthra', sku: '0031', category: 'cat-yantra', price: 1500, stock: 0 },
  { name: 'Vastu Dosha Yanthra', sku: '0032', category: 'cat-yantra', price: 1000, stock: 15 },
  { name: 'Vyapar Vridhi Yantra', sku: '0033', category: 'cat-yantra', price: 1500, stock: 0 },
  { name: 'Vyapar Vridhi Yantra', sku: '0034', category: 'cat-yantra', price: 1000, stock: 50 },
  { name: 'All Pendant', sku: '0035', category: 'cat-bracelet', price: 1000, stock: 20 },
  { name: 'Karungali bracelet Big', sku: '0036', category: 'cat-bracelet', price: 1500, stock: 0 },
  { name: 'Karungali Bracelet Small', sku: '0037', category: 'cat-bracelet', price: 1000, stock: 43 },
  { name: 'Ashta Lakshmi Chowki', sku: '0038', category: 'cat-chowki', price: 12000, stock: 1 },
  { name: 'Dasha Mahavidya Chowki (DMVC )', sku: '0039', category: 'cat-chowki', price: 15000, stock: 0 },
  { name: '7 Horse Photo Frame', sku: '0040', category: 'cat-general', price: 4000, stock: 18 },
  { name: 'Bagalamukhi Kit', sku: '0041', category: 'cat-kit', price: 2000, stock: 250 },
  { name: 'Dhanalaskhmi Kubera Bandari Kit', sku: '0042', category: 'cat-kit', price: 2500, stock: 110 },
  { name: 'Drusti Ring', sku: '0043', category: 'cat-ring', price: 2500, stock: 300 },
  { name: 'Karugali Mala ( Silver )', sku: '0044', category: 'cat-general', price: 2500, stock: 45 },
  { name: 'Karugali mala (Normal)', sku: '0045', category: 'cat-general', price: 2000, stock: 40 },
  { name: 'Keerthi Mukha', sku: '0046', category: 'cat-general', price: 3500, stock: 30 },
  { name: 'Lakshmi paduke', sku: '0047', category: 'cat-general', price: 10000, stock: 0 },
  { name: 'Lakshmi Pyramid', sku: '0048', category: 'cat-general', price: 4000, stock: 40 },
  { name: 'Laskhmi Kubera Bandari Yanthra', sku: '0049', category: 'cat-yantra', price: 1500, stock: 400 },
  { name: 'Meru Ring', sku: '0050', category: 'cat-ring', price: 2000, stock: 50 },
  { name: 'Naradhrushthi', sku: '0051', category: 'cat-general', price: 4000, stock: 38 },
  { name: 'Narmadeshwara Ling Big', sku: '0052', category: 'cat-general', price: 5000, stock: 30 },
  { name: 'Narmadeshwara Ling Small', sku: '0053', category: 'cat-general', price: 3000, stock: 50 },
  { name: 'Navartna Mala New', sku: '0054', category: 'cat-general', price: 2000, stock: 70 },
  { name: 'Navartna Mala Old', sku: '0055', category: 'cat-general', price: 1500, stock: 50 },
  { name: 'Navartna Ring', sku: '0056', category: 'cat-ring', price: 2500, stock: 276 },
  { name: 'Nazar Kit', sku: '0057', category: 'cat-kit', price: 2000, stock: 100 },
  { name: 'Rudraksha Karugali Mala', sku: '0058', category: 'cat-general', price: 2000, stock: 30 },
  { name: 'Saligrama', sku: '0059', category: 'cat-general', price: 500, stock: 420 },
  { name: 'Shani Kit', sku: '0060', category: 'cat-kit', price: 2000, stock: 500 },
  { name: 'Subramanya statue', sku: '0061', category: 'cat-general', price: 2000, stock: 30 },
  { name: 'Sampurna Yantra', sku: '0062', category: 'cat-yantra', price: 5500, stock: 50 },
  { name: 'Sarva Kasta Nivarana Yantra', sku: '0063', category: 'cat-yantra', price: 5000, stock: 13 },
  { name: 'Blue Ring', sku: '0064', category: 'cat-ring', price: 2000, stock: 50 },
  { name: 'Coral Ring', sku: '0065', category: 'cat-ring', price: 2000, stock: 40 },
  { name: 'Green Ring', sku: '0066', category: 'cat-ring', price: 2000, stock: 22 },
  { name: 'Opal Ring', sku: '0067', category: 'cat-ring', price: 2000, stock: 5 },
  { name: 'Pearl Ring', sku: '0068', category: 'cat-ring', price: 2000, stock: 38 },
  { name: 'Ruby Ring', sku: '0069', category: 'cat-ring', price: 2000, stock: 45 },
  { name: 'Yellow Ring', sku: '0070', category: 'cat-ring', price: 2000, stock: 22 },
  { name: 'Thulasi Mala', sku: '0071', category: 'cat-general', price: 100, stock: 240 }
];

export const products = rawProductsList.map((p, idx) => ({
  id: 'prod-' + p.sku,
  sku: p.sku,
  name: p.name,
  category_id: p.category,
  price: p.price,
  cost: Math.round(p.price * 0.45),
  stock: p.stock,
  min_stock: p.stock <= 5 ? 5 : Math.min(10, Math.round(p.stock * 0.15)),
  warehouse_id: idx % 3 === 0 ? 'wh-blr' : (idx % 3 === 1 ? 'wh-hbl' : 'wh-mys'),
  supplier_id: idx % 3 === 0 ? 'sup-apex' : (idx % 3 === 1 ? 'sup-zenith' : 'sup-nexa')
}));

export const sampleLeadNames = [
  'Ramesh Patel', 'Anil Deshmukh', 'Sunita Reddy', 'Vikram Malhotra', 'Snehal Joshi',
  'Mohan Lal', 'Deepa Krishnan', 'Arvind Kejriwal', 'Pooja Agarwal', 'Kiran Bedi',
  'Rohan Kulkarni', 'Suresh Raina', 'Manish Sharma', 'Praveen Kumar', 'Swati Deshpande',
  'Harish Shenoy', 'Rashmi Hegde', 'Vinay Varma', 'Jyoti Prasad', 'Amitabh Sengupta',
  'Chandan Mukherjee', 'Bhavna Dave', 'Naveen Jindal', 'Geeta Phogat', 'Nitin Gadkari',
  'Tarun Gogoi', 'Simran Kaur', 'Jaspreet Bumrah', 'Shalini Kapoor', 'Gopal Das',
  'Prashant Bhushan', 'Meenakshi Sundaram', 'Ajay Piramal', 'Vandana Luthra', 'Kishore Biyani',
  'Radha Sharma', 'Gaurav Gill', 'Anuradha Paul', 'Sudhir Rao', 'Kavita Krishnamurthy',
  'Dinesh Karthik', 'Sandhya Roy', 'Vijay Mallya', 'Bhanu Pratap', 'Nandini Das',
  'Chetan Bhagat', 'Arundhati Roy', 'Umesh Yadav', 'Ishant Sharma', 'Smriti Mandhana',
  'Harmanpreet Kaur', 'Mithali Raj', 'Sania Mirza', 'Leander Paes', 'Mahesh Bhupathi',
  'Abhinav Bindra', 'Gagan Narang', 'Pankaj Advani', 'Mary Kom', 'Vijender Singh',
  'Sushil Kumar', 'Bajrang Punia', 'Vinesh Phogat', 'Sakshi Malik', 'Ravi Dahiya',
  'Neeraj Chopra', 'Hima Das', 'Dutee Chand', 'PT Usha', 'Milkha Singh',
  'Devendra Jhajharia', 'Deepa Malik', 'Mariyappan Thangavelu', 'Avani Lekhara', 'Sumit Antil',
  'Pramod Bhagat', 'Krishna Nagar', 'Bhavina Patel', 'Sharad Kumar', 'Singhraj Adhana',
  'Sunil Chhetri', 'Bhaichung Bhutia', 'Subrata Paul', 'Gurpreet Singh Sandhu', 'Sandesh Jhingan',
  'Manpreet Singh', 'PR Sreejesh', 'Harmanpreet Singh', 'Rupinder Pal Singh', 'Lalit Upadhyay',
  'Viswanathan Anand', 'Rameshbabu Praggnanandhaa', 'Gukesh D', 'Vidit Gujrathi', 'Koneru Humpy',
  'Harika Dronavalli', 'Tania Sachdev', 'Arjun Erigaisi', 'Nihal Sarin', 'Pentala Harikrishna',
  'Shankar Mahadevan', 'Sonu Nigam', 'Shreya Ghoshal', 'Arijit Singh', 'Sunidhi Chauhan'
];
